name: Build nightly

on:
  schedule:
    - cron: '30 5 * * *'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    if: github.repository == 'tquic-group/tquic-example-rust'
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - uses: actions/checkout@v4
      with:
        repository: Tencent/tquic
        path: deps/tquic
        submodules: 'recursive'
    - name: Update rust
      run: rustup update
    - name: Overriding with lastest tquic
      run: |
        echo "paths = [\"$GITHUB_WORKSPACE/deps/tquic\"]" > $HOME/.cargo/config.toml
    - name: Build TQUIC examples
      run: cargo build --all --verbose
